spring:
  application:
    name: mudanza-service
  data:
    mongodb: 
      uri: mongodb://mongodb-service:27017/mudanza
            
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: TRACE